name: build

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.REGISTRY_TAG }}:${{ github.sha }}

      - 
        name: "[ArgoCd] Download values.yaml"
        run: |
            RESPONSE=$(curl --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_PASSWORD }}" "https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/repository/files/blog.nullx.me%2Fvalues.yaml?ref=master")
            FILE_CONTENT=$(echo $RESPONSE | jq -r .content | base64 -d)
            export TEMP_FILE=$(mktemp)
            echo "$FILE_CONTENT" > $TEMP_FILE

      -
        name: "[ArgoCd] Edit values.yaml"
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image = "${{ secrets.REGISTRY_TAG }}:${{ github.sha }}"' $TEMP_FILE

      - 
        name: "[ArgoCd] Upload values.yaml"
        run: |
            CONTENT=$(cat $TEMP_FILE | base64)
            PUT_RESPONSE=$(curl --request PUT --header 'PRIVATE-TOKEN: ${{ secrets.GITLAB_PASSWORD }}' --header "Content-Type: application/json" --data '{"branch": "master", "author_email": "${{ secrets.GITLAB_AUTHOR_EMAIL }}", "author_name": "${{ secrets.GITLAB_AUTHOR_NAME }}", "content": "'"$CONTENT"'", "commit_message": "Update blog.nullx.me to ${{ secrets.REGISTRY_TAG }}:${{ github.sha }}"}' "https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/repository/files/blog.nullx.me%2Fvalues.yaml")
            echo $PUT_RESPONSE

      -
        name: "[ArgoCd] Clean up"
        run: |
            rm $TEMP_FILE


            